var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var MagazineObject=function(){function c(a,b,c,e,f){var g=this;void 0===b&&(b="");void 0===c&&(c="");void 0===e&&(e=0);void 0===f&&(f=null);this.magID=this.htmlContainer="";this.params=null;this.fallback_order=["html5","flash","js"];this.playerType="";this.protocol="https:";this.completeLoad=!1;this.canvasID="juice";this.hIdx=0;this.vta=!1;this.parentRef=null;this.has_load_lead_hornet=this.has_load_lead_js=this.has_load_lead_html5mobile=this.has_load_lead_html5=this.loadEagle=this.localPlayer=!1;
this.parentRef=a;"undefined"===typeof window.accessOfParentIFrameNotPossible&&(window.accessOfParentIFrameNotPossible=!1);this.params=null==f?{}:f;if(""===b){try{console.log("%c[Y] No container provided - using 'body' instead ","color:#e65117")}catch(k){}b="body"}this.htmlContainer=b;this.magID=c;this.hIdx=e;this.canvasID="juice";"undefined"===typeof this.params.fallback_order&&(this.params.fallback_order="hornet,html5,flash,js");"undefined"===typeof this.params.singlepageViewOn&&(this.params.singlepageViewOn=
"0");"undefined"===typeof this.params.canvasFSBGColor&&(this.params.canvasFSBGColor="standard");"undefined"===typeof this.params.fsbgcolor&&(this.params.fsbgcolor="standard");"undefined"===typeof this.params.playerElementFSRecom&&(this.params.playerElementFSRecom="on");"undefined"===typeof this.params.playerElementFSPrint&&(this.params.playerElementFSPrint="on");"undefined"===typeof this.params.playerElementFSDownload&&(this.params.playerElementFSDownload="on");"undefined"===typeof this.params.playerElementFSShareLinks&&
(this.params.playerElementFSShareLinks="on");"undefined"===typeof this.params.playerElementOverview&&(this.params.playerElementOverview="on");"undefined"===typeof this.params.playerElementPoweredBy&&(this.params.playerElementPoweredBy="on");"undefined"===typeof this.params.playerElementLogo&&(this.params.playerElementLogo="on");"undefined"===typeof this.params.playerElementPageNumbers&&(this.params.playerElementPageNumbers="on");"undefined"===typeof this.params.playerElementSearchEmbed&&(this.params.playerElementSearchEmbed=
"on");"undefined"===typeof this.params.hideOuterShadows&&(this.params.hideOuterShadows="0");"undefined"===typeof this.params.hideInnerShadows&&(this.params.hideInnerShadows="0");"undefined"===typeof this.params.author&&(this.params.author="");"undefined"===typeof this.params.canvasBGColor&&(this.params.canvasBGColor="transparent");"undefined"===typeof this.params.embedded&&(this.params.embedded=!1);"undefined"===typeof this.params.preview_image&&(this.params.preview_image="");"undefined"===typeof this.params.isFSOverlay&&
(this.params.isFSOverlay="0");"undefined"===typeof this.params.lang&&(this.params.lang="en");"undefined"===typeof this.params.c2rOnOff&&(this.params.c2rOnOff="on");"undefined"===typeof this.params.c2rURL&&(this.params.c2rURL="");"undefined"===typeof this.params.c2rMode&&(this.params.c2rMode="fullscreen");"undefined"===typeof this.params.c2rType&&(this.params.c2rType="buttonClassic");"undefined"===typeof this.params.scrollToPlayer&&(this.params.scrollToPlayer="off");"undefined"===typeof this.params.gaTracking&&
(this.params.gaTracking="on");"undefined"===typeof this.params.reg_source&&(this.params.reg_source="yumpu");"undefined"===typeof this.params.iconsColor&&(this.params.iconsColor="ffffff");"undefined"===typeof this.params.arrowsColor&&(this.params.arrowsColor="ffffff");(a=(a="undefined"===typeof this.params.c2rText?!0:!1)||""!==this.params.c2rText&&" "!==this.params.c2rText?a:!0)&&(this.params.c2rText="de"===this.params.lang?"Vergr\u00f6\u00dfern":"Click to read");"undefined"===typeof this.params.startpage&&
(this.params.startpage=0);"undefined"===typeof this.params.autoflip&&(this.params.autoflip=0);"undefined"===typeof this.params.origin&&(this.params.origin="origin");"undefined"===typeof this.params.ydomain&&(this.params.ydomain=0<=window.location.href.indexOf("https")?"https://":"http://",0<=window.location.href.indexOf("local.yumpu.com")?this.params.ydomain+="local.yumpu.com/":this.params.ydomain+=0<=window.location.href.indexOf("dev.yumpu.com")?"dev.yumpu.com/":"www.yumpu.com/");0<=this.params.ydomain.indexOf(".yumpu.com")&&
0<=this.params.ydomain.indexOf("http:")&&(this.params.ydomain=this.params.ydomain.replace("http:","https:"));"undefined"===typeof this.params.embed_id&&(this.params.embed_id="");"undefined"===typeof this.params.disableMobileFullscreen&&(this.params.disableMobileFullscreen=!1);"undefined"===typeof this.params.viewMode&&"1"===this.params.singlepageViewOn&&(this.params.viewMode="single");"undefined"===typeof this.params.useWebGL&&(this.params.useWebGL=!0);"undefined"===typeof this.params.fps&&(this.params.fps=
!1);"undefined"===typeof this.params.showLogs&&(this.params.showLogs=!1);"undefined"===typeof this.params.openView&&(this.params.openView="normal");"fullscreen"===this.params.openView&&"undefined"==typeof document.fullscreenEnabled&&(this.params.openView="newtab");this.create_global_variables();if(window.jQuery){try{"undefined"===typeof window.$&&(window.$=window.jQuery)}catch(k){}this.init()}else a=location.protocol,"http:"!==a&&"https:"!==a&&(a="http:"),b=document.createElement("script"),b.onload=
function(){g.init()},b.src=a+"//web.archive.org/web/20220514142530/https://players.yumpu.com/libs/jquery-3.4.1.min.js",document.head.appendChild(b)}c.prototype.create_global_variables=function(){for(var a in this.params)this[a]=this.params[a];this.magazineID=this.magID};c.prototype.init=function(){"undefined"!==typeof this.params.fallback_order&&1<=this.params.fallback_order.split(",").length&&(this.fallback_order=this.params.fallback_order.split(","));this.include_bind_functionality_for_old_browser();this.playerType=this.determine_frontend();
"newtab"===this.params.openView?this.magID&&window.open(this.params.ydomain+this.params.lang+"/document/read/"+this.magID,"_blank").focus():("fullscreen"===this.params.openView&&(this.htmlContainerElement=document.getElementById(this.htmlContainer.replace("#","")),this.htmlContainerElement.style.backgroundColor="#253139",this.htmlContainerElement.style.width="100%",this.htmlContainerElement.style.height="100%",this.htmlContainerElement.requestFullscreen(),document.addEventListener("fullscreenchange",
this.fullscreenChangeHandler.bind(this))),"hornet"===this.playerType||"hornetmobile"===this.playerType?"undefined"===typeof window.yumpu_load_hornet_ressources_lead?(window.yumpu_load_hornet_ressources_lead=this,this.has_load_lead_hornet=!0,this.init_continue()):"undefined"!==typeof window.yumpu_load_hornet_ressources_done?window.yumpu_load_hornet_ressources_done&&this.init_continue():("undefined"===typeof window.yumpu_load_hornet_queue&&(window.yumpu_load_hornet_queue=[]),window.yumpu_load_hornet_queue.push(this)):
"html5"===this.playerType?"undefined"===typeof window.yumpu_load_html5_ressources_lead?(window.yumpu_load_html5_ressources_lead=this,this.has_load_lead_html5=!0,this.init_continue()):"undefined"!==typeof window.yumpu_load_html5_ressources_done?window.yumpu_load_html5_ressources_done&&this.init_continue():("undefined"===typeof window.yumpu_load_html5_queue&&(window.yumpu_load_html5_queue=[]),window.yumpu_load_html5_queue.push(this)):"html5mobile"===this.playerType?"undefined"===typeof window.yumpu_load_html5mobile_ressources_lead?
(window.yumpu_load_html5mobile_ressources_lead=this,this.has_load_lead_html5mobile=!0,this.init_continue()):"undefined"!==typeof window.yumpu_load_html5mobile_ressources_done?window.yumpu_load_html5mobile_ressources_done&&this.init_continue():("undefined"===typeof window.yumpu_load_html5mobile_queue&&(window.yumpu_load_html5mobile_queue=[]),window.yumpu_load_html5mobile_queue.push(this)):"js"===this.playerType?"undefined"===typeof window.yumpu_load_js_ressources_lead?(window.yumpu_load_js_ressources_lead=
this,this.has_load_lead_js=!0,this.init_continue()):"undefined"!==typeof window.yumpu_load_js_ressources_done?window.yumpu_load_js_ressources_done&&this.init_continue():("undefined"===typeof window.yumpu_load_js_queue&&(window.yumpu_load_js_queue=[]),window.yumpu_load_js_queue.push(this)):this.init_continue())};c.prototype.init_continue=function(a){var b=this;void 0===a&&(a=!1);try{$.ajaxSetup({cache:!0})}catch(c){}try{this.canvasID="hornet"===this.playerType||"hornetmobile"===this.playerType?"yp-player-canvas-hornet_"+
this.hIdx.toString():"juice_"+this.hIdx.toString();this.protocol=location.protocol;"http:"!==this.protocol&&"https:"!==this.protocol&&(this.protocol="http:");try{"undefined"===typeof $&&"undefined"!==typeof jQuery&&(window.$=jQuery)}catch(c){}var l=this.protocol,e=l=0<=window.location.href.indexOf("localplayers.yumpu.com")?l+"//web.archive.org/web/20220514142530/https://localplayers.yumpu.com/":0<=window.location.href.indexOf("dev.yumpu.com")?l+"//web.archive.org/web/20220514142530/https://dev.yumpu.com/":0<=window.location.href.indexOf("local.yumpu.com")?l+"//web.archive.org/web/20220514142530/https://local.yumpu.com/":l+
"//web.archive.org/web/20220514142530/https://www.yumpu.com/";"undefined"!==typeof this.params.ydomain&&10<this.params.ydomain.length&&(e=this.params.ydomain);0<=e.indexOf(".yumpu.com")&&0<=e.indexOf("http:")&&(e=e.replace("http:","https:"));var f=(0<=l.indexOf("localplayers.yumpu.com")||0<=l.indexOf("local.yumpu.com"))&&this.localPlayer?!0:!1,g=!0===f?"https://web.archive.org/web/20220514142530/http://local.yumpu.com:81/player/juice_v2/juiceClasses-min.js":"https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/juiceClasses-min.js",k=!0===f?"https://web.archive.org/web/20220514142530/http://local.yumpu.com:81/player/juice_v2/juiceMobileClasses-min.js":
"https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/juiceMobileClasses-min.js",f=!0===f?"https://web.archive.org/web/20220514142530/http://local.yumpu.com:81/player/Hornet/bin/dist/HornetPackage.min.js":"https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/HornetPackage.min.js";this.vta=!0;var d=!1;if("undefined"!==typeof this.params.ydomain){var h=this.params.embedded;this.params.embedded&&0>this.params.ydomain.indexOf("yumpu.com")&&(h=!1);!h&&0>this.params.ydomain.indexOf("yumpu.com")&&(d=!0)}d||this.load_and_run_additional_tracking();(this.params.embedded||0>location.href.indexOf(".yumpu.com/"))&&
Yumpu.mainRef.hideIntercomBubbleHandler();switch(this.playerType){case "hornet":case "hornetmobile":a?this.load_magazine_data_json(this.protocol,this.magID,this.playerType):((0<=navigator.userAgent.toLowerCase().indexOf("trident/5.")||0<=navigator.userAgent.toLowerCase().indexOf("MSIE 9."))&&$.getScript("https://web.archive.org/web/20220514142530/https://players.yumpu.com/libs/ie9_float32array_support.js",function(){console.log("IE9 detected - loaded float32array support")}),$.getScript(f,function(){$(document).ready(function(){b.load_magazine_data_json(b.protocol,
b.magID,b.playerType);try{if(b.has_load_lead_hornet&&(window.yumpu_load_hornet_ressources_done=!0,"undefined"!==typeof window.yumpu_load_hornet_queue&&0<window.yumpu_load_hornet_queue.length))for(var a=0;a<window.yumpu_load_hornet_queue.length;a++)window.yumpu_load_hornet_queue[a].init_continue(!0)}catch(d){console.log("[Y] err delegating load lead hornet: "+d)}})}));break;case "html5":a?this.load_magazine_data_json(this.protocol,this.magID,this.playerType):($.getScript(this.protocol+"//web.archive.org/web/20220514142530/https://imasdk.googleapis.com/js/sdkloader/ima3.js",
function(){}),$.getScript("https://web.archive.org/web/20220514142530/https://players.yumpu.com/libs/createjs-2015.11.26.min.js",function(){$.getScript(g,function(a,d,c){$(document).ready(function(){b.load_magazine_data_json(b.protocol,b.magID,b.playerType);try{if(b.has_load_lead_html5&&(window.yumpu_load_html5_ressources_done=!0,"undefined"!==typeof window.yumpu_load_html5_queue&&0<window.yumpu_load_html5_queue.length))for(var a=0;a<window.yumpu_load_html5_queue.length;a++)window.yumpu_load_html5_queue[a].init_continue(!0)}catch(d){console.log("[Y] err delegating load lead h5: "+
d)}})})}));break;case "html5mobile":a?this.load_magazine_data_json(this.protocol,this.magID,this.playerType):$.getScript("https://web.archive.org/web/20220514142530/https://players.yumpu.com/libs/createjs-2015.11.26.min.js",function(a,d,c){$.getScript(k,function(a,d,c){$(document).ready(function(){b.load_magazine_data_json(b.protocol,b.magID,b.playerType);try{if(b.has_load_lead_html5mobile&&"undefined"!==typeof window.yumpu_load_html5mobile_queue&&0<window.yumpu_load_html5mobile_queue.length){for(var a=0;a<window.yumpu_load_html5mobile_queue.length;a++)window.yumpu_load_html5mobile_queue[a].init_continue(!0);
"undefined"===typeof window.yumpu_load_html5mobile_ressources_done&&(window.yumpu_load_html5mobile_ressources_done=!0)}}catch(d){console.log("[Y] err delegating load lead h5m: "+d)}})})});break;case "flash":create_and_load_flash_player(this.protocol,this.magID,this);break;case "js":if(a)this.trigger_jhook_init(e,l);else{a=/MSIE ([0-9]{1,}[.0-9]{0,})/;var h=9,m=0<=navigator.userAgent.toLowerCase().indexOf("msie ")?!0:!1;m&&null!=a.exec(navigator.userAgent)&&(h=parseFloat(RegExp.$1));m&&8>=h?$.getScript("https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/jHook.min.js",
function(a,b,d){this.trigger_jhook_init(e,l)}.bind(this)):$.getScript("https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/jHook.min.js",function(a,d,c){$(document).ready(function(){b.trigger_jhook_init(e,l)})})}}this.log_player_type()}catch(c){}};c.prototype.log_player_type=function(){try{window.ga("yptrack.send","event",{eventAction:this.playerType,eventCategory:"yp_tc_playertype",eventLabel:this.playerType})}catch(a){}};c.prototype.trigger_jhook_init=function(a,b){var c=0<=window.location.href.indexOf("local.yumpu")?
"local":"www",c=0<=window.location.href.indexOf("dev.yumpu")?"dev":c,e="undefined"!==typeof this.params.password?"?password="+this.params.password:"",f="undefined"!==typeof this.params.ref?(""===e?"?":"&")+"ref="+this.params.ref:"",g="undefined"!==typeof this.params.secureHash?"/"+this.params.secureHash:"";0<=a.indexOf(".yumpu.com")?create_jhook(this,this.htmlContainer,this.magID,this.protocol+"//"+c+".yumpu.com/en/document/json/"+this.magID+g+e+f):create_jhook(this,this.htmlContainer,this.magID,
a+"document/json/"+this.magID+g+e+f);try{if(this.has_load_lead_js&&"undefined"!==typeof window.yumpu_load_js_queue&&0<window.yumpu_load_js_queue.length){for(c=0;c<window.yumpu_load_js_queue.length;c++)window.yumpu_load_js_queue[c].init_continue(!0);"undefined"===typeof window.yumpu_load_js_ressources_done&&(window.yumpu_load_js_ressources_done=!0)}}catch(k){console.log("[Y] err delegating load lead js: "+k)}};c.prototype.include_bind_functionality_for_old_browser=function(){try{Function.prototype.bind||
(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,e=function(){},f=function(){return c.apply(this instanceof e&&a?this:a,b.concat(Array.prototype.slice.call(arguments)))};e.prototype=this.prototype;f.prototype=new e;return f})}catch(a){console.log("[Y] could not include bind: "+a)}};c.prototype.determine_frontend=function(){return this.is_mobile()?
"hornetmobile":"hornet"};c.prototype.is_mobile=function(){return/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test(navigator.userAgent)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,
4))||void 0!==window.orientation?!0:!1};c.prototype.has_flash=function(){for(var a=0;a<navigator.plugins.length;a++)if(-1<navigator.plugins[a].name.toLowerCase().indexOf("flash"))return!0;try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),!0}catch(b){return!1}};c.prototype.is_IE=function(){return 0<window.navigator.userAgent.indexOf("MSIE ")||0<window.navigator.userAgent.indexOf("Trident/")?!0:!1};c.prototype.check_certain_IE=function(){var a=window.navigator.userAgent;return 0<a.indexOf("Trident/6.0")?
!0:0<a.indexOf("Trident/5.0")?!0:!1};c.prototype.is_newest_IE=function(){return 0<window.navigator.userAgent.indexOf("Trident/7")?!0:!1};c.prototype.is_newer_browser_blocking_flash=function(){var a=window.navigator.userAgent.indexOf("Chrome/");if(0<=a){var b=window.navigator.userAgent.indexOf(" ",a+7),a=window.navigator.userAgent.substring(a+7,b).split(".");if(3<=a.length&&45<=parseInt(a[0])&&(0<parseInt(a[1])||0===parseInt(a[1])&&2454<=parseInt(a[2])))return!0}return!1};c.prototype.is_oldSafari=
function(){if(1<window.navigator.userAgent.indexOf("Mac")&&/^((?!chrome).)*safari/i.test(window.navigator.userAgent)&&window.navigator.userAgent.match(/Version\/[\d\.]+.*Safari/)){var a="."===window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("Version/")+9,1)?parseInt(window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("Version/")+8,1)):parseInt(window.navigator.userAgent.substr(window.navigator.userAgent.indexOf("Version/")+8,2));if(!isNaN(a))return 7>=a?!0:!1}return!1};
c.prototype.onResizeJHookFallback=function(a){try{this.jhookFallback.resize()}catch(b){}};c.prototype.onResizeHook=function(a){try{$("#embed_movie"+this.hIdx.toString()).css("min-height",$(this.htmlContainer).height()-10+"px")}catch(b){}};c.prototype.loadingFailedExitFullscreen=function(){try{var a=window.document;(a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen).call(window.document)}catch(b){}};c.prototype.load_magazine_data_json=function(a,b,c){"hornet"===this.playerType||
"hornetmobile"===this.playerType?!this.params.embedded||"fullscreen"===this.params.openView||0<window.location.href.indexOf("/magazines/edit/")?this.checkIfHtmlRendered():this.create_hornet_player():"html5"===this.playerType?this.create_html5_player():"html5mobile"===this.playerType&&this.create_html5_mobile_player()};c.prototype.create_hornet_player=function(){try{if(this.params.embedded&&0>=window.location.href.indexOf("/embed/"))this.create_iframe_embed();else if(null!==document.getElementById(this.htmlContainer.replace("#",
""))){this.canvas=$('<canvas id="'+this.canvasID+'" class="juice" style="display:inline-block; position:relative; top:0px; left:0px; width:100%; height:100%;"></canvas>')[0];$(this.htmlContainer).append(this.canvas);$(this.htmlContainer).css("overflow","hidden");$(this.htmlContainer).css("padding","0px");var a="yumpu_hornet_"+this.hIdx.toString();window[a]=new window.Hornet.Main(null,this,a,this.is_mobile());this.completeLoad=!0}}catch(b){alert("Error loading magazine. Please reload page and try again. ")}};
c.prototype.create_iframe_embed=function(){var a=1,b=1,c=0,e=1,f=1,g="ffffff",k="ffffff",d=1,h=1,m=1,p=1;void 0!==this.params.canvasFSBGColor&&"standard"!==this.params.canvasFSBGColor&&0==this.params.canvasFSBGColor.indexOf("#")&&(this.params.canvasFSBGColor=this.params.canvasFSBGColor.split("#")[1]);void 0!==this.params.canvasBGColor&&"standard"!==this.params.canvasBGColor&&0==this.params.canvasBGColor.indexOf("#")&&(this.params.canvasBGColor=this.params.canvasBGColor.split("#")[1]);var a="on"===
this.params.playerElementSearchEmbed?1:0,b="1"===this.params.singlepageViewOn?1:0,e="on"===this.params.playerElementPageNumbers?1:0,f="on"===this.params.playerElementLogo?1:0,g=""===this.params.canvasFSBGColor?"253139":this.params.canvasFSBGColor,k=""===this.params.canvasBGColor?"253139":this.params.canvasBGColor,d="on"===this.params.playerElementFSShareLinks?1:0,h="on"===this.params.playerElementFSDownload?1:0,m="on"===this.params.playerElementFSPrint?1:0,p=this.params.startpage,c=this.params.autoflip,
q=this.params.embed_id,n=0<=location.href.indexOf("local.yumpu.com")||0<=location.href.indexOf("dev.yumpu.com")?"https://web.archive.org/web/20220514142530/https://dev.yumpu.com/":"https://web.archive.org/web/20220514142530/https://www.yumpu.com/";""===q&&"embed"===window.location.href.split("/")[4]&&"view"===window.location.href.split("/")[5]&&(q=window.location.href.split("/")[6]);n+=this.params.lang+"/embed/js/";n=""===q?n+this.magID:n+q;n+="?search="+a+"&autoflip="+c+"&startpage="+p+"&pageview="+b+"&pagenumber="+e+"&logo="+f+"&fsbgcolor="+g+"&bgcolor="+k+"&share="+d+"&download="+
h+"&print="+m;a=this.htmlContainer.substr(1);b=document.createElement("iframe");b.setAttribute("src",n);b.setAttribute("allowFullScreen","");b.style.width="100%";b.style.height="100%";document.getElementById(a).appendChild(b)};c.prototype.create_eagle_player=function(){if(0<window.location.href.indexOf("/magazines/edit/")||0<window.location.href.indexOf("/account/create"))this.htmlContainerElement=document.getElementById(this.htmlContainer.replace("#","")),this.htmlContainerElement.style.backgroundImage=
"linear-gradient(rgb(26, 51, 60), rgb(44, 101, 136))";var a=this.htmlContainer.replace("#","");this.eaglePlayer=new Eagle.Main({htmlContainer:a,jsonUrl:this.params.ydomain+this.params.lang+"/document/json2/"+this.magID,startPage:0,loadHtml:!0,onYumpu:!0,embedded:!1});this.eaglePlayer.createPlayer()};c.prototype.loadEaglePlayer=function(){var a=this,b=0<=location.href.indexOf("dev.yumpu.com")?"https://web.archive.org/web/20220514142530/https://dev-player.yumpu.news/eagle.js":"https://web.archive.org/web/20220514142530/https://player.yumpu.news/eagle.js";$.getScript(b,function(){$(document).ready(function(){a.create_eagle_player()})})};
c.prototype.fullscreenChangeHandler=function(){document.fullscreenElement||this.destroyPlayer()};c.prototype.destroyPlayer=function(){this.loadEagle&&(this.eaglePlayer.destroy(),this.loadEagle=!1);this.htmlContainerElement.innerHTML="";this.htmlContainerElement.removeAttribute("style");document.dispatchEvent(new CustomEvent("fullscreenCloseDestroy"))};c.prototype.checkIfHtmlRendered=function(){var a=this,b=0<=location.href.indexOf("local.yumpu.com")||0<=location.href.indexOf("dev.yumpu.com")?"https://web.archive.org/web/20220514142530/https://dev.yumpu.com/"+
this.params.lang+"/embed/get_document_info/":"https://web.archive.org/web/20220514142530/https://www.yumpu.com/"+this.params.lang+"/embed/get_document_info/",b=""===this.magID?b+this.params.embed_id:b+this.magID;$.ajax({type:"GET",url:b,dataType:"jsonp",xhrFields:{withCredentials:!0},cache:!0,success:function(b){a.loadEagle=b.data.html;a.loadEagle&&(a.params.embedded=!0);a.loadEagle&&"fullscreen"===a.params.openView||a.loadEagle&&(0<window.location.href.indexOf("/magazines/edit/")||0<window.location.href.indexOf("/account/create")||0<window.location.href.indexOf("/edit.html"))?
a.loadEaglePlayer():a.create_hornet_player()},error:function(a){console.log("%c[Y] err loading data ...")}})};c.prototype.create_html5_player=function(){try{if(null!==document.getElementById(this.htmlContainer.replace("#",""))){this.canvas=$('<canvas id="'+this.canvasID+'" class="juice" style="display:block; position:relative; top:0px; left:0px; width:100%; height:100%;" ></canvas>')[0];$(this.htmlContainer).append(this.canvas);$(this.htmlContainer).css("overflow","hidden");this.ctx=this.canvas.getContext("2d");
var a="yumpu_html5_"+this.canvasID;window[a]=new window.Juice(null,this,a);this.completeLoad=!0}}catch(b){alert("Error loading magazine. Please reload page and try again. ")}};c.prototype.create_html5_mobile_player=function(){this.canvas=$('<canvas id="'+this.canvasID+'" style="display:block; position:relative; top:0px; left:0px; width:100%; height:100%;" ></canvas>')[0];"#yumpudocumentcontainer"===this.htmlContainer&&($(this.htmlContainer).css("width",window.innerWidth+"px"),$(this.htmlContainer).css("height",
window.innerHeight+"px"));$(this.htmlContainer).append(this.canvas);$(this.htmlContainer).css("overflow","hidden");$(this.htmlContainer).css("padding","0px");this.ctx=this.canvas.getContext("2d");var a="yumpu_html5_"+this.canvasID;window[a]=new window.JuiceMobile(this.magJSON,this,a);this.completeLoad=!0};c.prototype.load_and_run_additional_tracking=function(){try{var a;a=0<=location.href.indexOf("local.yumpu.com")||0<=location.href.indexOf("dev.yumpu.com")||0<=location.href.indexOf("localplayers.yumpu.com")?
"UA-59582458-3":"UA-27868640-1";var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src="https://web.archive.org/web/20220514142530/https://www.googletagmanager.com/gtag/js?id="+a;var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c);window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};window.gtag("js",new Date);window.gtag("config",a)}catch(e){}};return c}();
function create_and_load_flash_player(c,a,b){var l=0<=window.location.href.indexOf("local.yumpu")?"local":"www",l=0<=window.location.href.indexOf("dev.yumpu")?"dev":l,e=!1;"undefined"!==typeof b.params.ydomain?0>b.params.ydomain.indexOf(".yumpu.com/")&&(e=!0):b.params.ydomain="";var f="undefined"!==typeof b.params.password?"?password="+b.params.password:"",g="undefined"!==typeof b.params.ref?(""===f?"?":"&")+"ref="+b.params.ref:"",k="undefined"!==typeof b.params.secureHash?"/"+b.params.secureHash:
"",d="",d=e?b.params.ydomain+"document/json/"+a+k+f+g:c+"//"+l+".yumpu.com/en/document/json/"+a+k+f+g;a="";a=0<=window.location.href.indexOf("local.yumpu.com/")?c+"//web.archive.org/web/20220514142530/https://s3.dualstack.eu-west-1.amazonaws.com/dev.yumpu/gueTest/main.swf?ref="+Math.floor(100*Math.random()):c+"//web.archive.org/web/20220514142530/https://hook.yumpu.com/hook/main.swf?ref="+encodeURIComponent(location.href);c=!1;try{window.accessOfParentIFrameNotPossible||"undefined"!==typeof window.parent.document&&window.parent.document&&(c=window.parent.document.webkitIsFullScreen||
window.parent.document.mozFullScreen||window.parent.document.fullscreenElement&&null!==window.parent.document.fullscreenElement)}catch(m){window.accessOfParentIFrameNotPossible=!0}d="json="+d+("&startpage="+b.params.startpage);d+="&bgcolor="+b.params.canvasBGColor;d+="&c2rOnOff="+b.params.c2rOnOff;d+="&c2rMode="+b.params.c2rMode;d+="&c2rURL="+b.params.c2rURL;d+="&c2rText="+b.params.c2rText;d+="&c2rType="+b.params.c2rType;d+="&origin="+b.params.origin;d+="&hideInnerShadows="+b.params.hideInnerShadows;
d+="&hideOuterShadows="+b.params.hideOuterShadows;d+="&elemPageNumbers="+b.params.playerElementPageNumbers;d+="&elemLogo="+b.params.playerElementLogo;d+="&elemLogoClaim="+b.params.playerElementPoweredBy;d+="&elemOverview="+b.params.playerElementOverview;d+="&elemFSShareLinks="+b.params.playerElementFSShareLinks;d+="&elemFSDownload="+b.params.playerElementFSDownload;d+="&elemFSPrint="+b.params.playerElementFSPrint;d+="&elemFSRecommended="+b.params.playerElementFSRecom;d+="&elemSearchEmbed="+b.params.playerElementSearchEmbed;
d+="&singlepageView="+b.params.singlepageViewOn;"undefined"!==typeof b.params.sharelocation&&(d+="&sharelocation="+b.params.sharelocation);c&&(d+="&html5FSActivated=1");"undefined"!==typeof b.params.canvasBGColor&&(d+="&bgcolor="+b.params.canvasBGColor);"undefined"!==typeof b.params.fsbgcolor&&(d+="&fsbgcolor="+b.params.fsbgcolor);"undefined"!==typeof b.params.aboteaser&&(d+="&aboteaser="+b.params.aboteaser);"undefined"!==typeof b.params.aboteaserLink&&(d+="&aboteaserLink="+b.params.aboteaserLink);
"undefined"!==typeof b.params.aboteaserAction&&(d+="&aboteaserAction="+b.params.aboteaserAction);"undefined"!==typeof b.params.prepage&&(d+="&prepage="+b.params.prepage);"undefined"!==typeof b.params.postpage&&(d+="&postpage="+b.params.postpage);"undefined"!==typeof b.params.withoutBranding&&(d+="&withoutBranding="+b.params.withoutBranding);"undefined"!==typeof b.params.mode&&(d+="&mode="+b.params.mode);"undefined"!==typeof b.params.gui&&(d+="&gui="+b.params.gui);"undefined"!==typeof b.params.autoflip&&
(d+="&autoflip="+b.params.autoflip);"undefined"!==typeof b.params.c2r&&(d+="&c2r="+b.params.c2r);"undefined"!==typeof b.params.topalign&&(d+="&topalign="+b.params.topalign);"undefined"!==typeof b.params.preset&&(d+="&preset="+b.params.preset);"undefined"!==typeof b.params.isFSOverlay&&(d+="&isFSOverlay="+b.params.isFSOverlay);"undefined"!==typeof b.params.preview_image&&(d=0<=b.params.preview_image.indexOf("image/remote?")?d+("&previewimage="+b.params.preview_image):d+("&previewimage="+encodeURIComponent(b.params.preview_image)));
d+="&ydomain="+b.params.ydomain;c="background-color:transparent; background:transparent;";"undefined"!==typeof b.params.canvasBGColor&&"transparent"!==b.params.canvasBGColor&&"standard"!==b.params.canvasBGColor&&(c="background-color:#"+b.params.canvasBGColor+";",$(b.htmlContainer).css("background-color","#"+b.params.canvasBGColor));var h="",h=h+('<object width="100%" height="100%" id="movie'+b.hIdx.toString()+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" style="'+c+'">'),h=h+('<param value="'+
a+'" name="movie"><param value="always" name="allowScriptAccess"><param value="true" name="allowfullscreen">'),h=h+'<param name="type" value="application/x-shockwave-flash" />',h=h+('<param value="'+d+'" name="FlashVars">'),h=h+'<param value="false" name="menu"><param value="transparent" name="wmode">',h=h+('<embed style="height:100%; background-image:url(); background-repeat:no-repeat; background-position:50% 50%;" name="movie" id="embed_movie'+b.hIdx.toString()+'" width="100%" height="100%" pluginspage="https://web.archive.org/web/20220514142530/http://www.adobe.com/go/getflashplayer" flashvars="'+
d+'" menu="false" wmode="transparent" allowfullscreen="true" allowscriptaccess="always" type="application/x-shockwave-flash" src="'+a+'">'),h=h+"</object>";$("#yumpudocumentcontainer").length?(window.completeLoad=!0,$(b.htmlContainer).html(h)):$(document).ready(function(){window.completeLoad=!0;console.log("**** ADDING HOOK **** ",$(b.htmlContainer).height());$(b.htmlContainer).html(h);$("#embed_movie"+b.hIdx.toString()).css("height","100%");0<=b.htmlContainer.indexOf("yp-account-magazine-edit-preview")&&
($("#embed_movie"+b.hIdx.toString()).css("min-height",$(b.htmlContainer).height()+"px"),window.onresize=b.onResizeHook.bind(b));$("#movie"+b.hIdx.toString()).css("height","100%")});try{0<=b.htmlContainer.indexOf("yp-account-magazine-edit-preview")&&(window.onresize=b.onResizeHook.bind(b))}catch(m){}}
function create_jhook(c,a,b,l){try{0===a.indexOf("#")&&(a=a.substring(1,a.length));c.jhookFallback=new window.JHookMain;c.jhookFallback.init(a,b,"",l,c.hIdx,c.params.embed_id);try{window.onresize=c.onResizeJHookFallback.bind(c)}catch(e){}}catch(e){console.log("[Y] err [jHook] init: "+e,"color:#e65117")}}
function jsToAs3_embedIsInFS(){try{if(!window.accessOfParentIFrameNotPossible)return window.parent?window.parent.document.fullscreenElement&&null!==window.parent.document.fullscreenElement||document.fullscreenElement&&null!==document.fullscreenElement||window.parent.document.fullScreen||window.parent.document.mozFullScreen||window.parent.document.webkitIsFullScreen||window.document.fullScreen||window.document.mozFullScreen||window.document.webkitIsFullScreen:!1}catch(c){return window.accessOfParentIFrameNotPossible=
!0,!1}}
function closeFSFromFlashEmbed(){try{window.accessOfParentIFrameNotPossible||(window.parent.document.exitFullscreen?window.parent.document.exitFullscreen():window.parent.document.webkitExitFullscreen?window.parent.document.webkitExitFullscreen():window.parent.document.msExitFullscreen?window.parent.document.msExitFullscreen():window.parent.document.mozCancelFullScreen?window.parent.document.mozCancelFullScreen():window.parent.document.cancelFullScreen&&window.parent.document.cancelFullScreen())}catch(c){window.accessOfParentIFrameNotPossible=!0,
console.log("%c[Y] closeFSFromFlashEmbed err: "+c,"color:#e65117")}}window.WebFontConfig={google:{families:["Open+Sans::latin"]}};(function(){var c=document.createElement("script");c.src=("https:"===document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";c.type="text/javascript";c.async=!0;var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)})();
(function(c){function a(a,b){var d=c.createEvent("Event");d.initEvent(a,!0,!1);b.dispatchEvent(d)}function b(b){b.stopPropagation();b.stopImmediatePropagation();c[d.enabled]=c[f.enabled];c[d.element]=c[f.element];a(d.events.change,b.target)}function l(b){a(d.events.error,b.target)}function e(a){return function(b,e){function l(){b();c.removeEventListener(f.events.change,l,!1)}function g(){e(new TypeError);c.removeEventListener(f.events.error,g,!1)}a!==d.exit||c[f.element]?(c.addEventListener(f.events.change,
l,!1),c.addEventListener(f.events.error,g,!1)):setTimeout(function(){e(new TypeError)},1)}}var f,g,k={w3:{enabled:"fullscreenEnabled",element:"fullscreenElement",request:"requestFullscreen",exit:"exitFullscreen",events:{change:"fullscreenchange",error:"fullscreenerror"}},webkit:{enabled:"webkitFullscreenEnabled",element:"webkitCurrentFullScreenElement",request:"webkitRequestFullscreen",exit:"webkitExitFullscreen",events:{change:"webkitfullscreenchange",error:"webkitfullscreenerror"}},moz:{enabled:"mozFullScreenEnabled",
element:"mozFullScreenElement",request:"mozRequestFullScreen",exit:"mozCancelFullScreen",events:{change:"mozfullscreenchange",error:"mozfullscreenerror"}},ms:{enabled:"msFullscreenEnabled",element:"msFullscreenElement",request:"msRequestFullscreen",exit:"msExitFullscreen",events:{change:"MSFullscreenChange",error:"MSFullscreenError"}}},d=k.w3;for(g in k)if(k[g].enabled in c){f=k[g];break}d.enabled in c||!f||(c.addEventListener(f.events.change,b,!1),c.addEventListener(f.events.error,l,!1),c[d.enabled]=
c[f.enabled],c[d.element]=c[f.element],c[d.exit]=function(){var a=c[f.exit]();return!a&&Promise?new Promise(e(d.exit)):a},Element.prototype[d.request]=function(){var a=this[f.request].apply(this,arguments);return!a&&Promise?new Promise(e(d.request)):a});return f})(document);
var BookshelfObject=function(){function c(a,b,c,e,f,g,k,d,h){var m=this;void 0===b&&(b="");void 0===c&&(c="");void 0===e&&(e="");void 0===f&&(f=null);void 0===g&&(g="0");void 0===k&&(k="m");void 0===d&&(d=0);void 0===h&&(h=null);this.userID=this.collectionID=this.htmlContainer="";this.params=null;this.fallback_order=["html5","flash","js"];this.playerType="";this.protocol="https:";this.completeLoad=!1;this.hIdx=0;this.idLead="#";this.refObj=0;this.has_load_lead_centipede=this.vta=!1;this.hIdx=a;this.htmlContainer=
b;this.collectionID=c;this.userID=e;this.jsonDataObj=f;this.playerBranding=g;this.coverSize=k;this.centipedeWidth=d;this.params=null==h?{}:h;"undefined"===typeof this.params.fullscreenLinkingActivated&&(this.params.fullscreenLinkingActivated="on");"undefined"===typeof this.params.isMobileDevice&&(this.params.isMobileDevice=this.isMobile());"undefined"===typeof this.params.yumpu_bookshelf_section_titles_on&&(this.params.yumpu_bookshelf_section_titles_on="on");"undefined"===typeof this.params.yumpu_bookshelf_target&&
(this.params.yumpu_bookshelf_target="magazinePage");"undefined"===typeof this.params.yumpu_bookshelf_flip_btn_color&&(this.params.yumpu_bookshelf_flip_btn_color="light");"undefined"===typeof this.params.yumpu_bookshelf_flip_throught_sections&&(this.params.yumpu_bookshelf_flip_throught_sections="on");"undefined"===typeof this.params.yumpu_bookshelf_align&&(this.params.yumpu_bookshelf_align="center");"undefined"===typeof this.params.yumpu_logo_on_or_off&&(this.params.yumpu_logo_on_or_off="on");"undefined"===
typeof this.params.title_font_color&&(this.params.title_font_color="FFFFFF");"undefined"===typeof this.params.usedFontFamily&&(this.params.usedFontFamily="Open Sans");"undefined"===typeof this.params.usedFontFamilyWebFontTitle&&(this.params.usedFontFamilyWebFontTitle="Open+Sans::latin");"undefined"===typeof this.params.ydomain&&(this.params.ydomain=0<=window.location.href.indexOf("https")?"https://":"http://",0<=window.location.href.indexOf("local.yumpu.com")?this.params.ydomain+="local.yumpu.com/":
this.params.ydomain+=0<=window.location.href.indexOf("dev.yumpu.com")?"dev.yumpu.com/":"www.yumpu.com/");"undefined"===typeof this.params.yumpu_bookshelf_target_url&&(this.params.yumpu_bookshelf_target_url=this.params.ydomain);"undefined"===typeof this.params.embedded&&(this.params.embedded=!1);"undefined"===typeof this.params.force_swf_overlay&&(this.params.force_swf_overlay="off");"undefined"===typeof this.params.yumpu_bookshelf_mag_title&&(this.params.yumpu_bookshelf_mag_title="no");"undefined"===
typeof this.params.autoflip&&(this.params.autoflip="0");for(var p in this.params)this[p]=this.params[p];if(""===this.htmlContainer){try{console.log("%c[Y] creating bookshelf: container missing","color:#e65117")}catch(q){}this.htmlContainer="body"}else"body"===this.htmlContainer.toLowerCase()?this.idLead="":"#"===this.htmlContainer.substr(0,1)?(this.idLead="#",this.htmlContainer=this.htmlContainer.substring(1,this.htmlContainer.length)):this.idLead="#";if(""===this.collectionID)try{console.log("%c[Y] creating bookshelf: collection ID missing",
"color:#e65117")}catch(q){}window.jQuery?this.init():(a=location.protocol,"http:"!==a&&"https:"!==a&&(a="http:"),b=document.createElement("script"),b.onload=function(){m.init()},b.src=a+"//web.archive.org/web/20220514142530/https://code.jquery.com/jquery-1.11.3.min.js",document.head.appendChild(b))}c.prototype.isMobile=function(){return/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino|android|ipad|playbook|silk/i.test(navigator.userAgent)||
/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,
4))?!0:!1};c.prototype.init=function(){this.load_web_font();"undefined"===typeof window.yumpu_load_centipede_ressources_lead?(window.yumpu_load_centipede_ressources_lead=this,this.has_load_lead_centipede=!0,this.init_continue()):"undefined"!==typeof window.yumpu_load_centipede_ressources_done?window.yumpu_load_centipede_ressources_done&&this.init_continue():("undefined"===typeof window.yumpu_load_centipede_queue&&(window.yumpu_load_centipede_queue=[]),window.yumpu_load_centipede_queue.push(this));
this.params.embedded&&Yumpu.mainRef.hideIntercomBubbleHandler()};c.prototype.init_continue=function(a){var b=this;void 0===a&&(a=!1);if(""===this.userID&&""!==this.collectionID&&null==this.jsonDataObj)$(this.idLead+this.htmlContainer).html('<center><br/><p style="font-family: Open Sans,Helvetica,Arial,sans-serif">Error creating bookshelf: username is missing! <br/>Please visit <a href="https://web.archive.org/web/20220514142530/http://developers.yumpu.com/frontend-api/frontend-api-introduction/">here</a> for detailed information about the implementation.</p></center>');
else{this.protocol=location.protocol;"http:"!==this.protocol&&"https:"!==this.protocol&&(this.protocol="http:");var c=this.protocol,c=0<=window.location.href.indexOf("localplayers.yumpu.com")?c+"//web.archive.org/web/20220514142530/https://localplayers.yumpu.com":0<=window.location.href.indexOf("dev.yumpu.com")||0<=window.location.href.indexOf(".devkiosk.io")?c+"//web.archive.org/web/20220514142530/https://dev.yumpu.com":c+"//web.archive.org/web/20220514142530/https://www.yumpu.com";this.vta=!0;this.load_and_run_additional_tracking();(this.params.embedded||0>location.href.indexOf(".yumpu.com/"))&&Yumpu.mainRef.hideIntercomBubbleHandler();
if(a)null==this.jsonDataObj?this.loadCollectionData():$(document).ready(function(){b.create_bookshelf()});else{var e=0<=c.indexOf("localplayers.yumpu.com")?"../../widget/centipede/bin/centipede.min.js":"https://web.archive.org/web/20220514142530/https://players.yumpu.com/classes/centipede.min.js";a=0<=c.indexOf("localplayers.yumpu.com")?"../../widget/centipede/bin/json2.js":"https://web.archive.org/web/20220514142530/https://players.yumpu.com/libs/json2.js";$.getScript(a,function(){$.getScript(e,function(a,c,e){try{if(b.has_load_lead_centipede&&"undefined"!==typeof window.yumpu_load_centipede_queue&&
0<window.yumpu_load_centipede_queue.length){for(a=0;a<window.yumpu_load_centipede_queue.length;a++)window.yumpu_load_centipede_queue[a].init_continue(!0);"undefined"===typeof window.yumpu_load_centipede_ressources_done&&(window.yumpu_load_centipede_ressources_done=!0)}}catch(d){console.log("[Y] err delegating load lead cp: "+d)}null==b.jsonDataObj?b.loadCollectionData():$(document).ready(function(){b.create_bookshelf()})})})}}};c.prototype.create_bookshelf=function(){var a=this;this.reset_containers();
var b="yumpu_bookshelf_"+this.hIdx;window[b]=new window.YumpuCentipede(this);window[b].init(b,this.idLead+this.htmlContainer,this.collectionID,this.jsonDataObj,this.playerBranding,this.coverSize,this.centipedeWidth);$(window).resize(function(){try{var b=!1;(b=window["yumpu_bookshelf_"+a.hIdx].pageContainer.fsActivated||window["yumpu_bookshelf_"+a.hIdx].pageContainer.fsHoldOn?!0:!1)||window["yumpu_bookshelf_"+a.hIdx].window_resize();a.reset_containers()}catch(c){try{console.log("%c[Y] cp - error resize window "+
c,"color:#e65117")}catch(f){}}})};c.prototype.reset_containers=function(){try{if(this.params.embedded){var a=window.innerWidth-60,b=window.innerHeight-60;$("#centipede_wrapper").css("width",a+"px").css("height",b+"px");$("#centipede_bookshelf").css("width",a+"px").css("height",b+"px").css("left","0").css("top","0")}}catch(c){}};c.prototype.load_web_font=function(){var a="undefined"!==typeof this.params.usedFontFamilyWebFontTitle?this.params.usedFontFamilyWebFontTitle:"Open+Sans::latin";try{"undefined"===
typeof window.WebFontConfig.google.families&&(window.WebFontConfig={google:{families:[a]}})}catch(c){window.WebFontConfig={google:{families:[a]}}}try{0>window.WebFontConfig.google.families.indexOf(a)&&window.WebFontConfig.google.families.push(a)}catch(c){window.WebFontConfig.google.families.push(a)}a=document.createElement("script");a.src=("https:"===document.location.protocol?"https":"http")+"://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";a.type="text/javascript";a.async=!0;var b=document.getElementsByTagName("script")[0];
b.parentNode.insertBefore(a,b)};c.prototype.loadCollectionData=function(){var a=this,b="",b=0<=this.params.ydomain.indexOf(".yumpu.com")?this.params.ydomain+"en/collections/json/"+this.userID+"/"+this.collectionID+"?callback=ytcbscoldat":this.params.ydomain+"collections/json/"+this.userID+"/"+this.collectionID+"?callback=ytcbscoldat";$.support.cors=!0;$.ajax({type:"GET",url:b,dataType:"jsonp",cache:!1,crossDomain:!0,success:function(b){a.jsonDataObj=b;a.create_bookshelf()},error:function(a){console.log("%c[Y] err loading data for Centipede[010]: "+
a.responseText,"color:#e65117")}})};c.prototype.load_and_run_additional_tracking=function(){try{(function(a,b,c,e,f,g,k){a.GoogleAnalyticsObject=f;a[f]=a[f]||function(){(a[f].q=a[f].q||[]).push(arguments)};a[f].l=1*new Date;g=b.createElement(c);k=b.getElementsByTagName(c)[0];g.async=1;g.src=e;k.parentNode.insertBefore(g,k)})(window,document,"script","https://web.archive.org/web/20220514142530/https://www.google-analytics.com/analytics.js","ga"),0<=location.href.indexOf("local.yumpu.com")||0<=location.href.indexOf("dev.yumpu.com")||0<=location.href.indexOf("localplayers.yumpu.com")?
window.ga("create","UA-59582458-3","auto","yptrack"):window.ga("create","UA-27868640-1","auto","yptrack")}catch(a){}};return c}(),Yumpu=function(){function c(a){var b=this;void 0===a&&(a="");this.bookshelfs=[];this.magazines=[];this.logo_embeds=[];this.dataMagID=this.dataEmbedID="";this.dataMagDivHeight=this.dataMagDivWidth=0;this.dataMagDivContainerName="";this.hideIntercomBubbleDT=this.hideIntercomBubbleIntervalID=0;this.hideIntercomBubbleLock=!1;this.devParam="";try{console.log("%c[Y] Toddycat * v1.6",
"background-color:#e65117; color:#ffffff")}catch(e){}window.yp_tc_start_time=(new Date).getTime();try{"undefined"===typeof $&&"undefined"!==typeof jQuery&&(window.$=jQuery)}catch(e){}try{"undefined"!==typeof $("#yumpuMagazineScript").attr("data-yumpu-embed-id")&&(this.dataEmbedID=$("#yumpuMagazineScript").attr("data-yumpu-embed-id"))}catch(e){}try{"undefined"!==typeof $("#yumpuMagazineScript").attr("data-yumpu-magazine-id")&&(this.dataMagID=$("#yumpuMagazineScript").attr("data-yumpu-magazine-id"))}catch(e){}try{"undefined"!==
typeof $("#yumpuMagazineScript").attr("data-yumpu-width")&&(this.dataMagDivWidth=isNaN(parseInt($("#yumpuMagazineScript").attr("data-yumpu-width")))?0:parseInt($("#yumpuMagazineScript").attr("data-yumpu-width")))}catch(e){}try{"undefined"!==typeof $("#yumpuMagazineScript").attr("data-yumpu-height")&&(this.dataMagDivHeight=isNaN(parseInt($("#yumpuMagazineScript").attr("data-yumpu-height")))?0:parseInt($("#yumpuMagazineScript").attr("data-yumpu-height")))}catch(e){}try{"undefined"!==typeof $("#yumpuMagazineScript").attr("data-yumpu-player-container")&&
(this.dataMagDivContainerName=$("#yumpuMagazineScript").attr("data-yumpu-player-container"))}catch(e){}if(""!==this.dataMagID){a="width:100%; height:100%;";0<this.dataMagDivWidth&&0<this.dataMagDivHeight&&""===this.dataMagDivContainerName?a="width:"+this.dataMagDivWidth.toString()+"px; height:"+this.dataMagDivHeight.toString()+"px;":0===this.dataMagDivWidth&&0===this.dataMagDivHeight&&""===this.dataMagDivContainerName&&(a="width:620px; height:550px;");var l=this.magazines.length.toString();this.dataMagDivContainer=
$('<div id="yumpuMagazine'+l+'" style="position:absolute; display:block; top:0px; bottom:0px; left:0px; '+a+' background-color:transparent; background:transparent;" ></canvas>')[0];""!==this.dataMagDivContainerName&&"body"!==this.dataMagDivContainerName?($("#"+this.dataMagDivContainerName).append(this.dataMagDivContainer).css("overflow","hidden"),this.resize_handling_html_container(),window.addEventListener("resize",function(a){b.resize_handling_html_container()})):$("body").append(this.dataMagDivContainer);
this.create_player("#yumpuMagazine"+l,this.dataMagID,{fallback_order:"html5,flash,js"})}else""!==this.dataEmbedID&&this.fetch_embed_data_from_hash(this.dataEmbedID);c.mainRef=this}c.prototype.hideIntercomBubbleHandler=function(){if(!this.hideIntercomBubbleLock){this.hideIntercomBubbleLock=!0;try{this.hideIntercomBubbleIntervalID=window.setInterval(this.hideIntercomBubble.bind(this),500)}catch(a){}}};c.prototype.resize_handling_html_container=function(){try{var a=0>this.magazines.length-1?"0":(this.magazines.length-
1).toString(),b=$("#"+this.dataMagDivContainerName).position().top,c=$("#"+this.dataMagDivContainerName).height(),e=$("#"+this.dataMagDivContainerName).width(),f=parseInt($("#"+this.dataMagDivContainerName).css("margin-top")),g=parseInt($("#"+this.dataMagDivContainerName).css("margin-left"));$("#yumpuMagazine"+a).css("top",(b+f).toString()+"px");$("#yumpuMagazine"+a).css("left",g.toString()+"px");$("#yumpuMagazine"+a).css("height",c.toString()+"px");$("#yumpuMagazine"+a).css("width",e.toString()+
"px")}catch(k){console.log("%c[Y] err resizing container "+k,"color:#e65117")}};c.prototype.create_player=function(a,b,c){void 0===a&&(a="");void 0===b&&(b="");void 0===c&&(c=null);try{return"undefined"===typeof window.createjs&&(window.createjs=window),this.magazines.push(new MagazineObject(this,a,b,this.magazines.length,c)),"success"}catch(e){return console.log("%c[Y] create_player error: "+e,"color:#e65117"),"error"}};c.prototype.create_bookshelf=function(a,b,c,e,f,g,k,d){void 0===a&&(a="");void 0===
b&&(b="");void 0===c&&(c="");void 0===e&&(e=null);void 0===f&&(f=null);void 0===g&&(g="0");void 0===k&&(k="m");void 0===d&&(d=0);try{var h=this.get_number_of_bookshelfs(),m=new BookshelfObject(h,a,b,c,f,g,k,d,e);this.bookshelfs.push(m);return"success"}catch(p){return console.log("%c[Y] create_bookshelf error:  "+p,"color:#e65117"),"error"}};c.prototype.create_logo_embed=function(a,b,c){};c.prototype.get_number_of_magazines=function(){return this.magazines.length};c.prototype.get_number_of_bookshelfs=
function(){return this.bookshelfs.length};c.prototype.get_number_of_logo_embeds=function(){return this.logo_embeds.length};c.prototype.dispose_container=function(a){void 0===a&&(a="");try{if(""!==a){for(var b=this.magazines.length,c=!1,e=b-1;0<=e;e--)if(this.magazines[e].htmlContainer===a){c=!0;if("undefined"!==typeof window["yumpu_html5_hornet_"+this.magazines[e].hIdx])try{window["yumpu_html5_hornet_"+this.magazines[e].hIdx].dispose()}catch(f){}else if("undefined"!==typeof window["yumpu_html5_juice_"+
this.magazines[e].hIdx])try{window["yumpu_html5_juice_"+this.magazines[e].hIdx].dispose()}catch(f){}$(a).empty();delete window["yumpu_html5_hornet_"+this.magazines[e].hIdx];delete window["yumpu_html5_juice_"+this.magazines[e].hIdx];window["yumpu_html5_hornet_"+this.magazines[e].hIdx]=null;window["yumpu_html5_juice_"+this.magazines[e].hIdx]=null;this.magazines[e]=null;delete this.magazines[e];this.magazines.splice(e,1);break}if(!c)for(b=this.bookshelfs.length,e=b-1;0<=e;e--)if(this.bookshelfs[e].htmlContainer===
a){window["yumpu_bookshelf_"+this.bookshelfs[e].hIdx].dispose();$(a).empty();delete window["yumpu_bookshelf_"+this.bookshelfs[e].hIdx];window["yumpu_bookshelf_"+this.bookshelfs[e].hIdx]=null;this.bookshelfs.splice(e,1);break}return!0}return!1}catch(f){return!1}};c.prototype.dispose_all=function(){try{for(var a=this.magazines.length,b=a-1;0<=b;b--)this.dispose_container(this.magazines[b].htmlContainer);a=this.bookshelfs.length;for(b=a-1;0<=b;b--)this.dispose_container(this.bookshelfs[b].htmlContainer);
return!0}catch(c){return!1}};c.prototype.embedHashDataLoaded=function(a){try{var b="width:100%; height:100%;";0<this.dataMagDivWidth&&0<this.dataMagDivHeight&&""===this.dataMagDivContainerName?b="width:"+this.dataMagDivWidth.toString()+"px; height:"+this.dataMagDivHeight.toString()+"px;":0===this.dataMagDivWidth&&0===this.dataMagDivHeight&&""===this.dataMagDivContainerName&&(b="width:620px; height:550px;");var c="background-color:transparent; background:transparent;";"undefined"!==typeof a.bgc&&(c=
"transparent"!==a.bgc&&"standard"!==a.bgc?"background-color:#"+a.bgc+";":c);var e=this.magazines.length.toString();this.dataMagDivContainer=$('<div id="yumpuMagazine'+e+'" style="position:absolute; display:block; top:0px; left:0px; '+b+" "+c+'" ></canvas>')[0];a.canvasBGColor=a.bgc;a.bgcolor=a.bgc;a.fsbgcolor=a.fsbgc;a.elemPageNumbers="2"===a.pePageNumbers?"off":"on";a.elemLogo="2"===a.peLogo?"off":"on";a.elemLogoClaim="2"===a.pePoweredBy?"off":"on";a.elemOverview="2"===a.peOverview?"off":"on";a.elemFSShareLinks=
"2"===a.pefShareLinks?"off":"on";a.elemFSDownload="2"===a.pefDownload?"off":"on";a.elemFSPrint="2"===a.pefPrint?"off":"on";a.elemFSRecommended="2"===a.pefRecom?"off":"on";a.gui="1";a.origin="yumpuEmbed";a.embedded=!0;a.smallFSActive=!1;a.autoplay=a.tAF;a.singlepageViewOn="single_page"===a.pv?"1":"0";a.singlepageViewOn="paper_view"===a.pv?"2":a.singlepageViewOn;a.preset=a.pres;a.mag_title=a.title;a.author=a.user_name;a.startpage=a.sp;a.embed_width=a.w;a.embed_height=a.h;a.ydomain=0<=window.location.href.indexOf("https")?
"https://":"http://";0<=window.location.href.indexOf("local.yumpu.com")?a.ydomain+="local.yumpu.com/":a.ydomain+=0<=window.location.href.indexOf("dev.yumpu.com")?"dev.yumpu.com/":"www.yumpu.com/";a.c2rMode=a.c2rtrgt;a.c2rURL=a.c2rurl;a.c2rText=a.c2rtxt;a.c2rType=a.c2rtype;a.c2rOnOff="2"===a.c2roff?"off":"on";a.c2rMobileOnOff="2"===a.c2rInMobile?"off":"on";a.fallback_order="html5,flash,js";"undefined"!==typeof a.tH5F&&(a.fallback_order="2"===a.tH5F?"flash,html5,js":a.fallback_order);""!==this.dataMagDivContainerName&&
"body"!==this.dataMagDivContainerName?($("#"+this.dataMagDivContainerName).append(this.dataMagDivContainer),this.create_player("#"+this.dataMagDivContainerName,a.document_id,a)):($("body").append(this.dataMagDivContainer),this.create_player("#yumpuMagazine"+e,a.document_id,a))}catch(f){console.log("%c[Y] err create mag. from embed data: "+f,"color:#e65117")}};c.prototype.fetch_embed_data_from_hash=function(a){var b=this,c=location.protocol;"http:"!==c&&"https:"!==c&&(c="http:");var e=0<=window.location.href.indexOf("dev.yumpu.com")?
"dev.yumpu.com":"www.yumpu.com",e=0<=window.location.href.indexOf("local.yumpu.com")?"local.yumpu.com":e;window.yembedcb=function(a){};$.support.cors=!0;$.ajax({type:"GET",url:c+"//"+e+"/en/embed/get_embed_data_jsonp/"+a+"?callback=yembedcb",dataType:"jsonp",crossDomain:!0,success:function(a){try{b.embedHashDataLoaded(a)}catch(c){}},error:function(a){console.log("%c[Y] error loading data - Yum0001: "+a,"color:#e65117")}})};c.prototype.hideIntercomBubble=function(){this.hideIntercomBubbleDT+=500;5E3<=
this.hideIntercomBubbleDT&&clearInterval(this.hideIntercomBubbleIntervalID);try{document.getElementById("intercom-frame").style.display="none"}catch(a){}try{document.getElementById("intercom-container").style.display="none"}catch(a){}};return c}();
try{var yp_toddycat_windows_onload=function(){document.getElementById("yumpuMagazineScript")&&(document.getElementById("yumpuMagazineScript").getAttribute("data-yumpu-embed-id")||document.getElementById("yumpuMagazineScript").getAttribute("data-yumpu-magazine-id"))&&new Yumpu},jQ=void 0;"undefined"!==typeof $?jQ=$:"undefined"!==typeof window.jQuery&&(jQ=window.jQuery);if("undefined"===typeof jQ){var protocol=location.protocol;"http:"!==protocol&&"https:"!==protocol&&(protocol="http:");var script=
document.createElement("script");script.src=protocol+"//web.archive.org/web/20220514142530/https://players.yumpu.com/libs/jquery-3.4.1.min.js";document.head.appendChild(script)}window.addEventListener("load",yp_toddycat_windows_onload)}catch(c){console.log("%c[Y] jQuery not defined","color:#e65117")};


}
/*
     FILE ARCHIVED ON 14:25:30 May 14, 2022 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 15:23:23 May 15, 2022.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 824.857
  exclusion.robots: 0.083
  exclusion.robots.policy: 0.077
  cdx.remote: 0.058
  esindex: 0.007
  LoadShardBlock: 220.898 (3)
  PetaboxLoader3.datanode: 200.293 (4)
  CDXLines.iter: 56.009 (3)
  load_resource: 178.778
  PetaboxLoader3.resolve: 46.855
*/